security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_AGENT: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:

        dev:
            pattern:  ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                csrf_provider: form.csrf_provider
                success_handler: redirect.after.login
            logout:
                path: /logout
                target: /login
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY   }
        - { path: ^/resetting, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/ajout, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/list, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/delete, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/modif, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/detail, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/user, role: ROLE_ADMIN }

